### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by asitplus-pteufl** [eu-digital-green-certificates/dgc-participating-countries#1]
As just discussed with Martin in the call.
Where is the best place for such discussions: https://github.com/ehn-digital-green-development/hcert-spec/issues/46
Would it make sense to have an overview repository here, where such general issues can be discussed?

**Comment by SchulzeStTSI** [comment]
Please push the discussions to : https://github.com/eu-digital-green-certificates/dgc-overview We collect there the important points into guides or move the guides to other sub repositories.
