### ISSUE TITLE
How to obtain access to the test gateway

### ISSUE THREAD

**Issue by ikarstein** [eu-digital-green-certificates/dgc-participating-countries#13]
I want to register for the test gateway, but I do not find the information how to contact the "Test Opterator" as stated in https://github.com/eu-digital-green-certificates/dgc-participating-countries/blob/main/gateway/OnboardingChecklist.md?plain=1#L24

**Comment by daniel-eder** [comment]
See https://github.com/eu-digital-green-certificates/dgc-overview/issues/56#issuecomment-986694777 and https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10
