### ISSUE TITLE
CSCA requirements

### ISSUE THREAD

**Issue by SZoerner** [eu-digital-green-certificates/dgc-participating-countries#2]
I have a clarification question regarding the Certificate Signing Certificate Authority (CSCA):
Could we use a public commercial CA root as CSCA -> a country-specific one (D-Trust for Germany), but one not exclusively used for the EU Gateway?

**Comment by dirkx** [comment]
The specification currently allows for any certificate (that is able to sign another certificate; so the (sub/chain)CA flag needs to be set to TRUE) to be permitted as a CSCA. A document detailing this was in the works - see the minutes from the last meeting.

**Comment by oliver-steinbrecher** [comment]
Thanks for your answer. Can this be considered as stable?

**Comment by dirkx** [comment]
Best we have now - but I would wait for the documented to be formally adopted - hopefully with the onboarding spec.

**Comment by psavva** [comment]
Following

**Comment by SZoerner** [comment]
@dirkx Are talking about [this document](https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md)?

**Comment by SchulzeStTSI** [comment]
@SZoerner Yes this is the document. It's open for review to 4.5.
