### ISSUE TITLE
How can we provide certificates for DGCG

### ISSUE THREAD

**Issue by stamo** [eu-digital-green-certificates/dgc-participating-countries#3]
Hi everyone, 
Please advice how to send **TLS**, **Upload** and **CSCA** certificates for the testing environment. We would like to test our implementation against it. 

In the documentation is said that we have to send them over an email, but I can not find this email anywhere. 

Thank you

**Comment by SchulzeStTSI** [comment]
@stamo A functional mailbox will be announced this week together with the test environment. After this announcement you can send your CRT files/PEM strings to this mailbox.

**Comment by daniel-eder** [comment]
Functional mailbox was announced to member states today.
