### ISSUE TITLE
Define all routes

### ISSUE THREAD

**Issue by louridas** [eu-digital-green-certificates/dgc-participating-countries#5]
Hello,

In the procedure it currently states:

> 4. Test the other Truslist Routes in the same style (e.g. with DSC/CSCA/Upload/Authentication...)

Could you please list all "the other Trustlist Routes" explicitly?

( Also note the typo, Truslist => Trustlist).

Thanks,

Panos.

**Comment by daniel-eder** [comment]
I believe at this point this issue is outdated - if the change is still necessary please comment so I can reopen
